name: llama-finetuning
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Core Python (compatible with RHEL 8.8)
  - python=3.11

  # PyTorch ecosystem for H100 GPUs (CUDA 12.1 compatible)
  - pytorch=2.2.0
  - pytorch-cuda=12.1
  - torchvision=0.17.0
  - torchaudio=2.2.0

  # Essential ML packages
  - numpy=1.24.4
  - scipy=1.11.4
  - pandas=2.1.4
  - scikit-learn=1.3.2

  # Development tools
  - pip=23.3.1
  - setuptools=68.2.2
  - wheel=0.42.0
  - git=2.42.0

  # System utilities
  - curl=8.4.0
  - wget=1.21.4
  - unzip=6.0

  # Jupyter for development
  - jupyter=1.0.0
  - notebook=7.0.6

  # Performance libraries
  - mkl=2023.2.0
  - blas=1.0

  # Pip packages (installed after conda packages)
  - pip:
      # HuggingFace ecosystem
      - transformers==4.45.0
      - accelerate==0.26.0
      - datasets==2.16.0
      - huggingface-hub==0.20.1
      - tokenizers==0.15.0

      # PEFT and training
      - peft==0.8.0
      - trl==0.7.10

      # Quantization
      - bitsandbytes==0.42.0

      # Monitoring and logging
      - wandb==0.16.1
      - tensorboard==2.15.1

      # Additional utilities
      - sentencepiece==0.1.99
      - protobuf==4.25.1
      - packaging==23.2
      - psutil==5.9.6

      # Data processing
      - pyarrow==14.0.1
      - dill==0.3.7
      - multiprocess==0.70.15
      - aiohttp==3.9.1

      # Spanish language support
      - spacy==3.7.2
      - es-core-news-sm @ https://github.com/explosion/spacy-models/releases/download/es_core_news_sm-3.7.0/es_core_news_sm-3.7.0-py3-none-any.whl